sudo: required
services:
  - docker

script:
  - docker build -t river0825/docker-with-compose ./docker-with-compose
  - docker build -t river0825/aws-eks-helm ./aws-eks-helm
  #- docker build -t river0825/magento-php:7.3-cli ./7.3-cli
  #- docker build -t river0825/magento-php:7.3-fpm ./7.3-fpm

after_success:
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push river0825/docker-with-compose
  - docker push river0825/aws-eks-helm
  #- docker push river0825/magento-php:7.3-cli
  #- docker push river0825/magento-php:7.3-fpm
