sudo: required
services:
  - docker

#before_install:
#  - docker build -t river0825/react-test -f ./checkpoint/client/Dockerfile.dev ./checkpoint/client/

script:
#  - docker run river0825/react-test npm test -- --coverage
  - docker build -t river0825/docker-with-compose ./docker-with-compose
after_success:
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push river0825/docker-with-compose

